# Generated by Django 5.2.7 on 2025-11-12 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommissionRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_name', models.CharField(help_text='Ex: Comissão Bionio (10%)', max_length=100)),
                ('source', models.CharField(db_index=True, help_text="O 'source' exato da tabela de Vendas (ex: Rovema Pay)", max_length=50, unique=True)),
                ('percentage', models.DecimalField(decimal_places=2, default=0.0, help_text='O valor da percentagem (ex: 10.5 para 10.5%)', max_digits=5)),
            ],
        ),
    ]
